name: ci

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: checking out
        uses: actions/checkout@v3
        with:
          path: tgt
      - name: build
        working-directory: tgt
        run: |
          make
